import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from 'sonner'

// Inter fontunu daha kapsamlı bir şekilde yapılandır
const inter = Inter({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-inter',
  // Font ağırlıklarını ekle
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning className={inter.variable}>
      <body className={`font-sans ${inter.className}`}>
        <ThemeProvider>

            {children}

        </ThemeProvider>
        
      </body>
    </html>
  );
}
